### ISSUE TITLE
Grunt won't compile

### ISSUE THREAD

**Issue by dfilan** [agentmodels/agentmodels.org#15]
When trying to update webppl with `sudo sh ./scripts/update-webppl`, all of the `npm install` commands work, but when it gets to `grunt compile:../webppl-timeit:../webppl-dp:../webppl-viz:../webppl-gridworld`, I get the error 

```
Warning: Task "compile:../webppl-timeit:../webppl-dp:../webppl-viz:../webppl-gridworld" not found. Use --force to continue.
Aborted due to warnings.
```

Googling suggests that the fix is to edit a gruntfile, but I can't find one in the place I would expect.

**Comment by stuhlmueller** [comment]
It looks like you might not be on the latest version of agentmodels. Verify?

**Comment by dfilan** [comment]
Yep, after upgrading agentmodels things are working fine.
