### ISSUE TITLE
viz.print => viz.auto

### ISSUE THREAD

**Issue by william-r-s** [agentmodels/agentmodels.org#23]
When I started looking through the code boxes, I found that viz.print failed everywhere with the error message "viz.print is not a function". Looks like it was renamed to viz.auto (and it looks like it works and produces sensible results when I substitute it in), see: https://github.com/probmods/webppl-viz/commit/a2f58c4a5314b8c6fd934d56f81bc275d07e34ec

**Comment by dfilan** [comment]
Thanks, have replaced everywhere.
