### ISSUE TITLE
Broken codeboxes in chapter 5c

### ISSUE THREAD

**Issue by william-r-s** [agentmodels/agentmodels.org#28]
A number of the codeboxes in the latter section of chapter 5c (http://agentmodels.org/chapters/5c-joint-inference.html) fail with the error:
makeRestaurantUtilityMDP is not defined

**Comment by dfilan** [comment]
Have removed the references to `makeRestaurantUtilityMDP`, which was renamed to `makeRestaurantUtilityFunction`.
