### ISSUE TITLE
viz.print

### ISSUE THREAD

**Issue by owainevans** [agentmodels/agentmodels.org#3]
looks like viz.print still has the old problem. error message is: 
k is not a function

**Comment by stuhlmueller** [comment]
Yes, fixing this requires a change to webppl-editor (as described [here](https://github.com/probmods/webppl-editor/commit/4cc5c4eab8640c96c42097c2ad27856cb2b7c8df#commitcomment-15782582)). I'll update this issue when it's done.

**Comment by stuhlmueller** [comment]
This works as of ab78c55eb5543df05013158d59faadc769b3e747. See example [here](http://agentmodels.org/chapters/05-pomdp.html).
